version: '3.8'

networks:
  my-app-network:
    external: true

services:

  beacon-frontend:
    build:
      context: ./frontend
    command: yarn start
    container_name: beacon-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:8003
    ports:
      - 3001:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app